### ISSUE TITLE
hello i need help please error on   selfdestruct(admin);

### ISSUE THREAD

**Issue by hannibaljohn** [dappuniversity/token_sale#16]
Error: Attempting to run transaction which calls a contract function, but recipient address 0x50ff3bf83d309adad1bf04cc584d27dfd94d2917 is not a contract address
      at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
      at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
      at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
      at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
      at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
      at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
      at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
      at endReadableNT (_stream_readable.js:1094:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by mindfu** [comment]
I am also running into this issue.

**Comment by hannibaljohn** [comment]
hello mindfu i  already  figure out now, the answer is in the dappTokenSale.sol try to open and  you'll see the answer at the end  :)

**Comment by mindfu** [comment]
try to open the file on github?

**Comment by hannibaljohn** [comment]
yes :)

**Comment by mindfu** [comment]
Ok cool.  How was this fixed?

**Comment by sudiptab2100** [comment]
change the 'address admin;' in DappTokenSale.sol to 'address payable admin;'.
